### ISSUE TITLE
ExerciseViewer not visible

### ISSUE THREAD

**Issue by scrupeus** [ssaring/sportstracker#143]
Using v7.2.0 on OSX 10.11

Opening a GPX file in the ExerciseViewer worked a few times.  Later, I maximised the ExerciseViewer window, which also worked.  But when I tried to return it to normal size, the ExerciseViewer window disappeared - it is still listed under the Dock icon as being open, but it's not visible.  Opening other GPX files appears to work but, again, the windows are listed under the app's Dock icon and can be selected but they are not visible.  Note that resizing the window may not have anything to do with the problem, but it's a place to start looking.

I tried reinstalling, removing plist files, etc., but no luck.  I did capture the following logs from two separate attempts to open a GPX.  The same files had previously worked okay.  The only change with other failed attempts was the 'TexID' number changing.

2016-05-01 16:09:37 INFO de.saring.sportstracker.gui.STControllerImpl onOpenHrmFile Opening HRM file '/Users/username/Downloads/20160422.gpx' in ExerciseViewer... 
Incomplete attachment. (GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT)(FBO - 820)
Error creating framebuffer object with TexID 40)
2016-05-01 16:09:37.909 SportsTracker[539:11664] GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT_EXT
2016-05-01 16:09:38.302 SportsTracker[539:11664] GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT_EXT
2016-05-01 16:09:38.307 SportsTracker[539:11664] GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT_EXT
2016-05-01 16:09:42.296 SportsTracker[539:11664] GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT_EXT

2016-05-02 08:52:14 INFO de.saring.sportstracker.gui.STControllerImpl onOpenHrmFile Opening HRM file '/Users/username/Downloads/20160501.gpx' in ExerciseViewer... 
Incomplete attachment. (GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT)(FBO - 820)
Error creating framebuffer object with TexID 39)
2016-05-02 08:52:15.005 SportsTracker[539:11664] GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT_EXT
2016-05-02 08:52:15.245 SportsTracker[539:11664] GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT_EXT
2016-05-02 08:52:15.248 SportsTracker[539:11664] GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT_EXT
2016-05-02 08:52:19.321 SportsTracker[539:11664] GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT_EXT

**Comment by scrupeus** [comment]
I should have included...
I was using the bundled JRE.  I haven't tried standalone Java as it's not installed.

**Comment by ssaring** [comment]
Which tab has been opened in ExerciseViewer when the window gets hidden - the Map viewer?
It would be helpful if you could attach the GPX file for reproducing the problem.

**Comment by scrupeus** [comment]
All tabs had been opened at some time, but I don't know which was open when the error first occurred.  Now, I can never see the ExerciseViewer window - I select a file but the window does not appear.

I get the same error with any GPX file, including files that did work last week.  I have since tried some old GPX files and some sample GPX files from the net (see https://github.com/pytrainer/pytrainer/wiki/Sample-GPX- for example).  It is always the same problem.

I also just tried v7.1 - same problem.  It seems now the problem has happened once, there is some setting/preference somewhere that make it happen everytime.  Could it be that the window is off screen and hence giving errors when it tries to render?  Is there some other setting/preference that I can remove/reset?

**Comment by ssaring** [comment]
Thanks for the details. 

I've tried it with the GPX file from the pytrainer website and had no problems when resizing the ExerciseViewer window very often (with all tabs shown). There are also no warnings shown in the console. I've tested it on a MacBook Pro 13" (Intel IRIS 6100) with Mac OS X 10.11.4 and Java 8u92.

I think there are internal Java/JavaFX problems on your system, which could depend on the used graphic chip. The GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT_EXT warning messages are not logged by the SportsTracker application. If your system has a AMD / NVidia GPU you should try to disable it and use the internal Intel GPU instead. 

I'll close this issue, it does not makes sense to track internal Java bugs here. If you can provide a workaround, please create a pull request and reopen this issue.

Bye, Stefan
