### ISSUE TITLE
Configuring SportsTracker with Netbeans IDE

### ISSUE THREAD

**Issue by JerJohn15** [ssaring/sportstracker#147]
Hi,

So I came across this project the other day, was able to install and run it, from the sourceforge website, and now I'm trying to get it running it on my NetBeans IDE. I have followed the instructions from the "Developer's" section contained in the  [readme](https://raw.githubusercontent.com/ssaring/sportstracker/master/sportstracker/docs/README.txt) file here (I've also reposted this on my [wiki](https://github.com/JerJohn15/sportstracker/wiki/README-File) for better viewing) to install "SportsTracker" including the [JFreeChart](http://www.jfree.org/) and the [FIT library](https://www.thisisant.com/resources/fit) dependencies, but now I am stuck with proceeding forward in configuring my environment.

 To be more specific, I am trying to configure my version of the project with the FITSDK, but I cannot find any instructions on how to do this. Am I suppose to add a certain JAR file, from the Java folder in the FITSDK, to my build path location? If so, which project  folder? 

Also, in your Readme.txt file, you mentioned that you have created a repository that contains the Jfreechart and FITSDK files needed to install this, however that link is currently dead (I ended up installing them from their main websites, however, ANT+ does not seem to host previous versions of their SDK on their site as I could not find the required "16.50" version of the FITSDK you mention in your instructions so I had to install their "20.00" release. Would this still work with the current version of SportsTracker.

Let me know if I need to elaborate on anything.

**Comment by ssaring** [comment]
NetBeans should have no problems when opening the SportsTracker project as a Maven project. Just use "Open Project", select the project root directory and NetBeans should open the SportsTracker project and all its Maven submodules. NetBeans recognizes all the required dependencies from the pom.xml file(s), you don't need to setup/configure any libraries.
The Maven support of NetBeans is quite good, better than in Eclipse. I've just tested it on NetBeans 8.1, it works without problems.

Some of the libraries are provided in a Maven repository on my website at http://saring.de/st-maven-repo/ . This repo is not dead, it just can't be accessed from a web browser.

**Comment by JerJohn15** [comment]
Hello Stefan,

I just recently ran the application, and everything seems to be working now.
