### ISSUE TITLE
Could not find or load main class de.saring.sportstracker.gui.STApplication

### ISSUE THREAD

**Issue by asomers** [ssaring/sportstracker#150]
Trying to run sportstracker on TrueOS (a distribution of FreeBSD) I get the following error.  If I unzip the jar file, I can see that the STApplication.class file is there.

java -jar sportstracker-7.2.0.jar 
Error: Could not find or load main class de.saring.sportstracker.gui.STApplication

uname -a
FreeBSD threonine.lauralan.noip.me 12.0-CURRENT FreeBSD 12.0-CURRENT #8 a212210(drm-next-4.7): Tue Sep  6 12:20:35 UTC 2016     root@gauntlet:/usr/obj/usr/src/sys/GENERIC  amd64

**Comment by ssaring** [comment]
What kind of Java you are running on TrueOS? SportsTracker requires at least JDK 8u60. AFAIK there are no official binaries of the Oracle JDK available for FreeBSD, maybe there is an appropriate OpenJDK version. 
With OpenJDK you can get some problems in font rendering, some people reported such issues. I always recommend to use the latest Oracle JDK.

**Comment by asomers** [comment]
I'm running 8u102 of OpenJDK.

> java -version
openjdk version "1.8.0_102"
OpenJDK Runtime Environment (build 1.8.0_102-b14)
OpenJDK 64-Bit Server VM (build 25.102-b14, mixed mode)

I previously ran SportsTracker 7.0.0 on Linux with OpenJDK7u111.  When was the requirement changed to OpenJDK 8?

**Comment by ssaring** [comment]
Strange, 8u102 is the most recent version of Java. Are you sure that JavaFX is included in your installed OpenJDK package. 
It seems, that at least on Ubuntu Linux JavaFX is a separate package for OpenJDK (see http://stackoverflow.com/questions/34243982/why-is-javafx-is-not-included-in-openjdk-8-on-ubuntu-wily-15-10 ), is this also the case on TrueOS?

**Comment by asomers** [comment]
That was it.  Installing openjfx8 fixed it.  Such an oddly useless error message from OpenJDK, though.  Thanks for the quick help.

**Comment by ssaring** [comment]
Nice. You're right, the OpenJDK error message is misleading.
I had no idea that ST runs on FreeBSD, do you have any problems with OpenJDK, e.g. with the font rendering? Would be nice if you could send me a screenshot.
