### ISSUE TITLE
Curve smoothing in diagramm view

### ISSUE THREAD

**Issue by sl0wman** [ssaring/sportstracker#153]
Hi Stefan,
is it possible to add a smoothing filter to the diagram view to remove some spikes? This would be great especially for indoor (treadmill) runs with speed / distance measurement via footpod, which is probably somewhat inaccurate. Below is an example diagram: a treadmill run with nearly constant speed, but the log shows many spikes. 

![diagram](https://cloud.githubusercontent.com/assets/25465774/22482664/4275f186-e7fa-11e6-8853-06d4591c4632.png)

Maybe a sliding average filter can solve this problem. If possible, selectable and adjustable for each graph.

kind regards,
Matthias

**Comment by ssaring** [comment]
Implemented and merged with pull request #156.
