### ISSUE TITLE
RunCadence from Garmin footpod

### ISSUE THREAD

**Issue by sl0wman** [ssaring/sportstracker#154]
Hi Stefan,
i use a Garmin Forerunner 405 with SDM3 Footpod. The footpod allows to track the steps per time - the run cadence. It would be great if you can append the "RunCadence" parameter to the Garmin import filter, so that we can evaluate this parameter too :-). And, is it possible to display more than two graphs in the exercise viewer?

Below is an TCX track log with RunCadence data.
[Example.tcx.tar.gz](https://github.com/ssaring/sportstracker/files/743115/Example.tcx.tar.gz)

Regards,
Matthias

**Comment by ssaring** [comment]
Added support in PR #155.
