### ISSUE TITLE
Cannot parse Garmin Edge 820 files

### ISSUE THREAD

**Issue by jmrius** [ssaring/sportstracker#159]
I got a new Edge 820 and sportstracker cannot parse the .fit files.
It parsed successfully Garmin Edge 500 and 520 files.

Some clues:
- I can parse the Edge 820 .fit files with my own python script using fitparse module (https://github.com/dtcooper/python-fitparse)
- Pytrainer software from Ubuntu repository can also parse the Edge 820 .fit
- TurtleSport software (http://turtlesport.sourceforge.net/EN/home.html) is not able to parse the Edge 820 .fit

**Comment by ssaring** [comment]
Sounds like the files of the Edge 820 contain some extensions which need the latest FIT parser library from Garmin. I don't have a 820, so please provide a simple exercise file for reproducing the problem. 
It would be great if you could also add a screenshot for this exercise which contains the exercise data, then we're able to add an appropriate unit test.

**Comment by jmrius** [comment]
Dear Stefan,

Please find attached all my edge 820 exercises so far.

You can see the graphs if you follow me on Strava (Juan M Rius). The
graph for the longest ride (2017-05-13) as shown in my own python
program is:

Best regards,

Juan

**Comment by ssaring** [comment]
I'm not able to find any attachments here, where have you stored them?
Please attach just one example file and if possible a screenshot of it's data, I would suggest you not to upload all your personal training data.

Bye, Stefan

**Comment by jmrius** [comment]
Please find the file attached

**Comment by ssaring** [comment]
Sorry, I can't find any attached files in this issue here. 
Have you answered by using your email client and added the attachment there? This will probably not work, you need to attach the file directly on the GitHub issue page.

**Comment by jmrius** [comment]
The files are attached bellow. Thanks for your help!
Juan

[2017-05-13-08-18-55.zip](https://github.com/ssaring/sportstracker/files/1016091/2017-05-13-08-18-55.zip)
![2017-05-13-08-18-55](https://cloud.githubusercontent.com/assets/28727567/26275218/20c880a0-3d5c-11e7-86e1-0503ac09065e.png)

**Comment by ssaring** [comment]
Thanks for the test file, I can reproduce the problem now.

**Comment by ssaring** [comment]
Has been fixed by using the new Garmin FIT SDK (pull request #161), Edge 820 exercise files are supported now. Probably also all other Garmin models which are using the new protocol format 2.0.

**Comment by jmrius** [comment]
Thanks, Stefan. How could I get updated .jar files? The git repository
only contains the sources.

Juan

**Comment by ssaring** [comment]
Sounds like it's a problem for you to create a build. 
If you can't wait for the next release, send me your system informations via email and I'll provide you a pre-release in the next days.

Bye, Stefan

**Comment by jmrius** [comment]
Dear Stefan,

Regarding your Sportstracker update to import Garmin Edge 820 files, I
downloaded the Git project and tried unsuccessfully to create a build. I
installed some of the requirements specified in your README.txt file:

- Maven
- Groovy
- IntelliJ, NetBeans and Eclipse IDE's and tried all of them.

I got many compilation errors, probably due to missing libraries or plugins.

I have never programmed in Java, so it is my first time trying to
compile a Java project. I usually program in C, Python or Matlab.

Could you please send me a pre-release, or at least the compiled .jar
file that must be replaced?

My system is Ubuntu 16.09 (soon will be upgraded to 17.04).

Thank you for your help and best regards,

Juan

**Comment by ssaring** [comment]
I'll try to provide you a pre-release in the next few days, but I can't make a promise when it will be done.

Bye, Stefan

**Comment by ssaring** [comment]
Sorry, it took some time. You can download the latest snapshot with Edge 820 support as a DEB package for Debian and Ubuntu Linux here:

http://www.saring.de/st-snapshots/sportstracker-7.4.1-SNAPSHOT.deb
