### ISSUE TITLE
Correct introductory sentence

### ISSUE THREAD

**Issue by baimafeima** [ssaring/sportstracker#164]
> SportsTracker is a desktop application for people which want to record and analyze their sporting activities.

which --> who

**Comment by ssaring** [comment]
Where have you found it? It's already OK in the README.txt, GitHub description and the SportsTracker website. I've just found it on the saring.de landing page, I've fixed it there.

Thanks for the report!

**Comment by baimafeima** [comment]
It's still visible here on the GitHub page when you click on _Code_. The title page on GitHub.

**Comment by ssaring** [comment]
OK, I've missed that - now fixed too.

Thanks, Stefan
