### ISSUE TITLE
Trackpoint structures not similar in one GPX file results into error when parsing the data

### ISSUE THREAD

**Issue by entinenohjelmoija** [ssaring/sportstracker#174]
Hi there,
I'm new on the forum - looking to replace sports-tracker.com since they dropped Windows Phone support AND uploding workouts into www - and found another sportstracker :-)

How ever when trying with some of my old workouts I stumbled to issue when - for whatever reason the trackpoints do not have similar structure through whole file like:

      <trkpt lat="37.12215666666667" lon="-8.58392">
        <ele>12.0</ele>
        <time>2018-01-13T13:21:12Z</time>
        <extensions>
          <gpxtpx:TrackPointExtension>
            <gpxtpx:hr>157</gpxtpx:hr>
          </gpxtpx:TrackPointExtension>
        </extensions>
      </trkpt>
      <trkpt lat="37.12215666666667" lon="-8.58392">
        <ele>12.0</ele>
        <time>2018-01-13T13:21:13Z</time>
      </trkpt>

i.e. the hr extension is missing (or <ele>..), adding this exercise will result into error "Failed to read or parse HRM file".

My proposal would be to copy previous value of hr (or elevation,or..) to current trackpoint - if a value is needed - other wise could that trackpoint simply be left without valid hr (or <ele>, or ..) and simply continue parsing.

I've been using Nokia Lumia 530 with WP 8.1 for Sports Tracker v 1.0.1.12 from Sports Tracking Tecnologies Ltd. with their ST HRM2 belt - and would still like to use my that hw for my exercises.

Another issue (actually not for this forum?) is how to download batches of workouts from www.sports-tracker.com site? Seems to have +1500 there .... and how to get the new ones out of my Nokia phone??

br 
.ilkka.

**Comment by ssaring** [comment]
Hi,

your use case is quite specific, I don't think that there are many people with the same problems. It's sad that the exported exercise files from your Nokia software have structural problems.

I would suggest to implement a specific converter tool which fixes these file format errors and also performs the bulk import to the SportsTracker software. The data format for exercises in SportsTracker is very simple, just take a look to the exercises.xml file. You can alo find the XML schema definition in the project source code.

For simplicity and maintainability reasons I don't like to implement such specific features in SportsTracker itself. This makes the parsers even more complex and nobody ever knows whether all these workarounds are still used by anybody.

Bye, Stefan
