### ISSUE TITLE
Can't find variable: L with LeafletMapView

### ISSUE THREAD

**Issue by ThomasDaheim** [ssaring/sportstracker#175]
Hi all,

first of all thanks a lot for LeafletMapView! As pointed out in your blog all other options for maps in JavaFX are not really up to the task...

I'm trying to add LeafletMapView in my JavaFX project (https://github.com/ThomasDaheim/GPXEditor) instead of gluon maps. I'm able to show the map and center & zoom it to the track I want to show.
But when adding markers and tracks (addMarker and addTrack) I always get an error

```
Exception in thread "JavaFX Application Thread" netscape.javascript.JSException: ReferenceError: Can't find variable: L
	at com.sun.webkit.dom.JSObject.fwkMakeException(JSObject.java:156)
	at com.sun.webkit.WebPage.twkExecuteScript(Native Method)
	at com.sun.webkit.WebPage.executeScript(WebPage.java:1509)
	at javafx.scene.web.WebEngine.executeScript(WebEngine.java:1005)
	at de.saring.leafletmap.LeafletMapView.execScript(LeafletMapView.kt:180)
	at de.saring.leafletmap.LeafletMapView.addMarker(LeafletMapView.kt:145)
	at tf.gpx.edit.helper.GPXTrackviewer.setGPXWaypoints(GPXTrackviewer.java:137)
```
Which is surprising since "L" is found during executeMapSetupScripts(). Also the Main.kt is running fine in my environment.

Any hints where I could start digging to get this resolved?

**Comment by ssaring** [comment]
Hi Thomas,

could you please add the code snippets where you are using LeafletMapView? Without the sources I can't see the problem cause. 

Bye, Stefan

**Comment by ThomasDaheim** [comment]
Hi Stefan,

thanks for your quick response! I think I found the problem this morning under the shower :-) I didn't ensure in all cases to wait for worker.state ==  succeeded... Need to try this once I'm online again.

Bye, Thomas

**Comment by ssaring** [comment]
If you haven't done that, then it causes such problems. So I'll close this issue.

**Comment by JoshuaStapleton21** [comment]
Hello. I was wondering if you could provide more details on the code you used to check whether worker.state==succeeded?

**Comment by ThomasDaheim** [comment]
I use the following here:

```
        final CompletableFuture<Worker.State> cfMapLoadState = displayMap(myMapConfig);
        cfMapLoadState.whenComplete((Worker.State workerState, Throwable u) -> {
            isLoaded = true;

            initialize();
        });
```

Probably, I should be checking for value of Worker.State to be SUCCEEDED as well...

**Comment by JoshuaStapleton21** [comment]
@ThomasDaheim Thank you very much - this has been helpful. If it's not too much trouble, could you give me an example of the displayMap function or point to where it is located in your code?

**Comment by ThomasDaheim** [comment]
@JoshuaStapleton21 : See [here](https://github.com/ThomasDaheim/GPXEditor/blob/master/src/main/java/tf/gpx/edit/viewer/TrackMap.java).
