### ISSUE TITLE
Change color of track in LeafletMapView

### ISSUE THREAD

**Issue by ThomasDaheim** [ssaring/sportstracker#176]
I have seen that the color of a track is hard coded in LeafletMapView. How could I go ahead and extend LeafletMapView so that different colors can be used?

I tried to create my own java class that extends LeafletMapView. But that doesn't seem to be possible since  LeafletMapView is final in java :-(. Is there any other way to achieve the same?

**Comment by ssaring** [comment]
I would suggest you to create a fork and implement your missing feature, this should be quite easy and straight forward. It would be great if you could add the usage to the existing demo application and submit a pull request. I would like to integrate it, although I currently don't need it (yet).

**Comment by ThomasDaheim** [comment]
I would need to think about that. Since I don't speak kotlin I would need to start yet-another-programming-language... Maybe once I'm feeling bored and need a new challenge :-)
