### ISSUE TITLE
Additional documentation available for LeafletMapView?

### ISSUE THREAD

**Issue by ThomasDaheim** [ssaring/sportstracker#177]
And now after things are up & running come the questions :-) So I wanted to check if there is any add. documentation available for LeafletMapView?

E.g. with gloun maps I had one mapviewer and added & removed layers whenever a new gpx file from a list of files was selected. With LeafletMapView I would need to create a completely new LeafletMapView instance every time, right? Or at least I don't see an easy way to remove markers and tracks once added?

And I'm sure with each current functionality from gluon maps I would like to migrate will come new questions...

**Comment by ssaring** [comment]
You're right, LeafletMapView does not has the feature set like GluonMaps or other map components. It contains currently all the features which are needed for the SportsTracker application.

As I've already said, it should be quite easy to implement features like custom track colors or marker removal, it is very similar to the other existing methods in the LeafletMapView class. I know it's Kotlin, but its very easy to learn and the new methods are not much different from the others. All you need to do is to lookup the appropriate JavaScript calls in the (excellent) Leaflet.js documentation. But beware, you will like Kotlin in the end ;)

All the existing classes are documented with JavaDoc (or Kotlin Doc), so you should get all the documentation in the IDE code completion when you open the project or attach the sources.

If you plan to contribute your enhancement to the Leaflet/SportsTracker project, please document your added methods and integrate it to the demo application. This makes the usage easier for other developers.

Bye, Stefan
