### ISSUE TITLE
Calculate/Enter descent data from altitude 

### ISSUE THREAD

**Issue by alexjarosch** [ssaring/sportstracker#183]
Hi ssaring,

fantastic software and I love to use it! Here is a quick feature request and I hope its okay that I post it on github.

Would it be possibel to make an entry field for total descent in meters, similar to the total ascent that already exists? This field could either be filled with manual data or calculated from a connected HRM file.
Descent data per training or statistics of it are very interesting for sports like Skiing, Downhill MTB and such, so it would be great if sportstracker could support that.

Best,
Alex

**Comment by ssaring** [comment]
Hi Alex,

it's OK to post feature requests here - that's the place for it ;)
I've never thought about tracking the descent of an exercise, it doesn't matter for most endurance sport types. That was my assumption, maybe I'm wrong. 

One question: when you go skiing (downhill or cross country) or Downhill MTBing, isn't the ascent and the descent mostly the same? Bacause the start and the end position is mostly the same place.

Bye, Stefan

**Comment by alexjarosch** [comment]
Hi Stefan,

thanks for the fast reply.
Well, chair lifts (used in downhill MTB and downhill skiing) make a difference between ascent and descent totals over a training. For example, you might start your training on the mountain top and then ski/bike some slopes/runs. In the end you ski/bike down to the base station and you add descent meters which you did not actively ascent. For cross country skiing you are right, there the two values are mostly the same.

So I was wondering if it is a lot of work to add a descent tracking feature to sportstracker, if you agree that this is a feature you are interested in supporting.

Bye,
Alex

**Comment by ssaring** [comment]
OK, I see. We'll see when it can be added, maybe someone starts it before and provide a pull request.

If there are any other users who find the descent data usefull, please add a comment here. It's always good to see how big the demand is.

Bye, Stefan

**Comment by alexjarosch** [comment]
Sounds like a plan. BTW I just tested the downhill ski mode on my new sports watch and it tracks only downhill data to save battery. It uses its barometric altimeter to see if one goes up or down and then switches on the GPS to track the downhill tracks. So it can save about half the time energy.

Interestingly when I parse the corresponding fit file with your ExerciseViewer, the viewer calculates 0 m ascent as only descending data has been recorded.

This might be another motivation to actually implement descending data.

Bye for now,
Alex

**Comment by alexjarosch** [comment]
All good here, close.
