### ISSUE TITLE
Missing fonts

### ISSUE THREAD

**Issue by asomers** [ssaring/sportstracker#184]
After an update to my OS, SportsTracker's fonts stopped displaying properly.  Only numbers display, not text.  I suspect there's an undeclared dependency on some font package, but I don't know how to guess which.  Could you please give me a hint as to what I must install?
![sports_tracker_nofont](https://user-images.githubusercontent.com/129721/39086985-ce30c77c-4556-11e8-8bae-9a7ad42d3485.png)

**Comment by asomers** [comment]
This is TrueOS unstable (a FreeBSD derivative).  I've reported the issue upstream.  There are no updated packages, but I could try rebuilding from source.  Do you think the issue more likely resides in openjfx8-devel, openjdk8, or somewhere else?  I'm not a Java programmer.
https://github.com/trueos/trueos-core/issues/1546

**Comment by ssaring** [comment]
I'm sure that this is not a SportsTracker issue, that's why I close this issue here. Also I never used TrueOS, so I can't help you there, sorry. 

My suggestion is that there is a problem in the JavaFX or OpenJDK packages. These will have dependencies to other font packages or depand on a specific configuration which are not available.

**Comment by asomers** [comment]
Does SportsTracker use SWT ?  Looks like that is no longer enabled by default.

**Comment by ssaring** [comment]
No, SWT is not used. This is a 3rd party library, not part of the JDK.

**Comment by asomers** [comment]
I can't reproduce this bug with other Java programs.  However, other tiny Java utilities seem to be displaying their fonts differently than yours.  It's like they're trying to antialias but doing it badly.  Can you guess what the difference is?
![gpsprune](https://user-images.githubusercontent.com/129721/39098218-92c7e822-4624-11e8-8e1b-be471b52dd30.png)

**Comment by ssaring** [comment]
The difference is that the other programs are using the Swing UI library (at least your screenshot) and SportsTracker uses the new JavaFX library, which is not based on Swing.
