### ISSUE TITLE
gpx import fails when only some track points have heart rate information

### ISSUE THREAD

**Issue by frieger** [ssaring/sportstracker#188]
gpx import fails when only some track points have heart rate information.
There is a NullPointerException (as is to be expected) on line 287 of 
sportstracker/st-exerciseviewer/src/main/kotlin/de/saring/exerciseviewer/parser/impl/TopoGrafixGpxParser.kt

Since this is the code for computing the average heart rate, I suggest ignoring null values of the heart rate and adding a counter that counts the actual number of elements containing heart rate data instead of relying on the length of the element list.

**Comment by frieger** [comment]
For testing, I've attached a minimal example containing 3 track points. The first and third point have heart rate information, the second point does not. 

[sportstracker-gpximport-problem-minimal-example.gpx.zip](https://github.com/ssaring/sportstracker/files/2152946/sportstracker-gpximport-problem-minimal-example.gpx.zip)

Expected behavior: 1) Importing works, 2) Average heart rate = 100

**Comment by frieger** [comment]
This problem still persists in version 7.6.0

**Comment by ssaring** [comment]
Oops, for some reason I have not noticed that issue, sorry for that.
It has been fixed now, the attached example file can be imported as expected.
The change has been pushed to the master branch and will be available in the upcoming 7.6.1. release.

Bye, Stefan
