### ISSUE TITLE
μlogger GPX files in SportsTracker

### ISSUE THREAD

**Issue by benaustin** [ssaring/sportstracker#191]
I've used μlogger in the past and I like the tracking it does and I was hoping I could use it with SportsTracker (which I just found). I have made a test track to try it out. It wasn't very long but it's attached. When I try and attach it to an event I get an error that it was unable to parse the HRM file. I've attached the GPX file with .txt on the end. Can I add something to make it work for just the tracking? Add some superfluous HR data?

https://github.com/bfabiszewski/ulogger-server

[track1.gpx.txt](https://github.com/ssaring/sportstracker/files/2217612/track1.gpx.txt)

**Comment by ssaring** [comment]
The problem was that the GPX file contains partial altitude data only. Some trackpoint have an elevation, others not. I've implemented support to the GPX parser class, it's now able to handle it. It's allready available in the GitHub repository (master branch).

Bye, Stefan
