### ISSUE TITLE
Window Issue on Arch Linux

### ISSUE THREAD

**Issue by rocket-engineer** [ssaring/sportstracker#192]
Hi there,
I have a problem with windows on Arch Linux. The main window opens as expected, but additional windows just do not open properly. Instead, a small window appears that contains nothing. The only choice I have is to close the window (Alt-F4). I can import data (fit files), but I cannot process them (since the windows are not shown properly).

The only warning I get is:
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by impl.org.controlsfx.ImplUtils (file:/opt/SportsTracker/app/lib/controlsfx-9.0.0.jar) to method javafx.scene.Parent.getChildren()
WARNING: Please consider reporting this to the maintainers of impl.org.controlsfx.ImplUtils

Help is welcome ...

**Comment by rocket-engineer** [comment]
The ExerciseViewer works, but I cannot add exercises etc.

**Comment by ssaring** [comment]
Please provide some more details:

* Which OS version you're using?
* Which Desktop / Window Manager you're using?
* Which SportsTracker version you're using? Which package format?
* Are you using the internal Oracle JDK or the OpenJDK provided by ArchLinux?

Bye, Stefan

**Comment by rocket-engineer** [comment]
Hi Stefan,
- I use ArchLinux (rolling release), Linux: 4.18.6-arch1-1-ARCH
- Desktop: KDE5 (5.13.5-1)
- SportsTracker 7.5.0-1 (from https://aur.archlinux.org/packages/sportstracker)
- as far as I know the internal JDK is used (since the *.deb file was installed).

I also tried OpenJDK (jre10) along with the binary from sourceforge (7.5), but I got some errors at startup:
Error: Could not find or load main class de.saring.sportstracker.gui.STApplication
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application

I started it by "java -jar sportstracker-7.5.0.jar". java-10-openjdk is active.

**Comment by ssaring** [comment]
Using the internal JRE from the DEB package is perfect.
This could be an issue with the KDE window manager, I've already heard about similar problems. Could you please test it with another? I'm using Gnome without any problems.

**Comment by hchr** [comment]
I have the same issues on Manjaro KDE with the AUR package.
@rocket-engineer
You can workaround that small window.
First close the small window as you did.
Then click on the top left menu -> More Actions -> Special Application Settings
Size - Apply intially - something like 868,674
Close SportsTracker and start it again.
You should now have a normal window.

@ssaring
If I open a file with ctrl+o and click on a gpx file, it seems that SportsTracker thinks it's an HRM file:
"Opening HRM file '/home/gpx/2018-08-26_11-11_Sun.gpx"
and the only option in the window is to close it and nothing is added.
I can however, import the gpx file, if I drag and drop the gpx file in the Calender view.
I could be doing something wrong.......

**Comment by ssaring** [comment]
@hchr Thanks for sharing the workaround for KDE users.

The problem with opening HRM files (HRM stands for exercise files of any supported type) sounds related to the other KDE window management problems with Java applications. Do you see any exception while the Open-dialog stays open? You need to start the app from the terminal to see the exceptions.

**Comment by hchr** [comment]
Oh, I thought that HRM was HeartRateMonitor.

No excepitions, all I get is:
SportsTracker 
2018-09-21 11:43:32 INFO de.saring.sportstracker.gui.STDocumentImpl loadOptions Loading application options... 
2018-09-21 11:43:33 INFO de.saring.sportstracker.gui.STControllerImpl$LoadTask call Loading application data... 
2018-09-21 11:43:46 INFO de.saring.sportstracker.gui.STControllerImpl onOpenHrmFile Opening HRM file '/home/gpx/2018-09-05_14-56_Wed.gpx' in ExerciseViewer...

In the ExcerciseViewer window that opens up after opening the gpx, everything seems to be there.
It reads the gpx file correct and all the infos is there, but there is no way to save it. Only choice is to "Close"
![sportstracker-window](https://user-images.githubusercontent.com/6417330/45874819-61911c00-bd85-11e8-9604-44a83913e954.png)

**Comment by ssaring** [comment]
@hchr HRM stands for heartrate monitor, you're right. When speaking of HRM files I mean exercise files recorded by any heartrate monitor.

About your other problem with opening HRM files: this is all fine, you're just expecting another behavior.
The action "Open HRM file" just opens any supported HRM file and shows the content in the Exercise Viewer. It does not import or apply anything. It's called just "Open..."
The import of an HRM file can be done by drag & drop. You can drop a file to a free place in the calendar, then it creates a new exercise entry with the imported data. 
Or you can dop the file to an existing exercise entry in the calendar, then it attaches that file to the selected exercise entry.
I think these usage options are documented in the README.txt.

**Comment by ssaring** [comment]
I'm closing this issue, it seems to be a bug either in the KDE window manager for Java(FX) applications or in the Java(FX) implementation. We know the workaround now or there's the way of using an alternative window manager.
