### ISSUE TITLE
Can't compile code

### ISSUE THREAD

**Issue by Axlrck** [ssaring/sportstracker#199]
Hey there, when i try to run i have this error :

> Information:java: Errors occurred while compiling module 'st-util'
> Information:javac 1.8.0_31 was used to compile java sources
> Information:2019-01-17 11:27 - Compilation completed with 1 error and 0 warnings in 5 s 640 ms
> Error:java: invalid source release: 11

I loaded it with maven by the way...

Thanks

**Comment by ssaring** [comment]
You're using a Java 8 compiler, the latest SportsTracker needs Java 11 - as printed in the output.
