### ISSUE TITLE
transportability problem

### ISSUE THREAD

**Issue by freddugland** [ssaring/sportstracker#205]
Hello everyone,
I install sports tracker on a usb key but when I change my computer I can not read my personal data anymore.
Thank you for your help
I am a simple sportsman ..

**Comment by ssaring** [comment]
Hello Fred,

by default the application stores the data in the user home directory. This is e.g. "C:/Users/username/.sportstracker" on Windows or "/Users/username/.sportstracker" on macOS.

But there is also the "datadir" option, which can be used to store the application data in a specific directory, e.g. on the USB key. This has been implemented for such use cases as your USB key usage.

This option is documented in the README.txt (section "Installation and Start"): 
https://raw.githubusercontent.com/ssaring/sportstracker/master/sportstracker/docs/README.txt

Bye, Stefan

**Comment by freddugland** [comment]
salut stefan,
je te remercie de ton aide et de ta réponse rapide.
toute mes félicitation pour ton logiciel . encore merci




Le ven. 26 avr. 2019 à 20:16, Stefan Saring <notifications@github.com> a
écrit :
