### ISSUE TITLE
"supports OpenStreetMap, OpenCycleMap, HikeBikeMap, MtbMap and MapBox layers, more can be added easily"

### ISSUE THREAD

**Issue by ThomasDaheim** [ssaring/sportstracker#211]
After some time spent on other projects I'm now back to working with leafletmap. I wanted to do "more can be added easily" but failed. Not sure how to go about it?

I can see two options:

- extend enum MapLayer with entries that I want to add
- store return value of "L.control.layers(baseMaps, overlayMaps).addTo(myMap);" in LeafletMapView for later manipulation

Both would mean changing the existing code. I was hoping for some solution using configuration only but couldn't come up with one. How should this be done properly?

**Comment by ssaring** [comment]
The idea is to extend the MapLayer enum, this should be quite easy. Adding new layers via configuration is not supported. I assume that users of LeafletMapView clone the module anyway, such modifications shouldn't be a problem then.

If you think that such changes are interesting for other users too (or for SportsTracker), then it would be great if you file a PullRequest.

**Comment by ThomasDaheim** [comment]
So far I could add all my extension without having to fork. So I was hoping to keep it that way :-)

I will create a pull request with the following changes:

1. extended MapLayer with a satellite vie using ESRI
2. modifed LeafletMapView to store the return value of L.control.layers(baseMaps, overlayMaps).addTo(myMap);

#1 is my real aim here. But with #2 only I could add my layer afterwards as well... So I would be happy with change #2 alone.

**Comment by ssaring** [comment]
Both changes are OK for me, I've merged your PR. And I've done two minor fixes in my master branch.

The Esri satellite map layer looks interesting, also for SportsTracker users. Can it be added without legal problems to open source applications?

**Comment by ThomasDaheim** [comment]
Good question about the requirements to use ESRI!

Must confess that I have seen it in the example for leaflet-elevation [leaflet-elevation_toggable-charts](https://raruto.github.io/examples/leaflet-elevation/leaflet-elevation_toggable-charts.html) and have taken it from there.

Further digging reveals: https://github.com/esri/esri-leaflet#terms

"If you display an ArcGIS Online service in any Leaflet application, we require that you include Esri attribution and recognize data providers."

Since the ArcGIS API isn't used no developer account is required. So its only attribution and data providers.

Attribution we do, but we don't list the data providers yet. I have found an example for that under: http://bl.ocks.org/d3noob/8663620. Probably 'i-cubed, USDA, USGS, AEX, GeoEye, Getmapping, Aerogrid, IGN, IGP, UPR-EGP, and the GIS User Community' should be added to the attribution to have the data providers included as well.

**Comment by ssaring** [comment]
Ooops, that's a really long attribution text. Can this be shortened somehow?
Thanks for the info!

**Comment by ThomasDaheim** [comment]
According to https://support.esri.com/en/technical-article/000012040 there doesn't seem to be a short version :-(

Sources: "Esri, DigitalGlobe, GeoEye, i-cubed, USDA FSA, USGS, AEX, Getmapping, Aerogrid, IGN, IGP, swisstopo, and the GIS User Community"

Maybe reduce the font size ;-)

**Comment by ThomasDaheim** [comment]
OMG, they have a "World Ocean Basemap" https://www.arcgis.com/home/item.html?id=1e126e7520f9466c9ca28b8f28b5e500

Not useful for any routing but cool as hell...

**Comment by ssaring** [comment]
OK, so we have to use the long text version, I'll add it.

And yes, the ocean map is really cool!

**Comment by ssaring** [comment]
Done, proper attribution now.
