### ISSUE TITLE
Possibility to add api keys for map layers?

### ISSUE THREAD

**Issue by ThomasDaheim** [ssaring/sportstracker#216]
I have just gotten myself an api key for the OpenCycleMap. Now I'm wondering how to add this during map initialization?

What would need to happen is a change to the URL as used in MapLayer.OPENCYCLEMAP. But I can't see a way to do this? Of course I can now do it after map initialization by fiddling around with controlLayer but maybe there is a more straightforward way to do this?

**Comment by ThomasDaheim** [comment]
Have to answer myself...

There is no easy way to do this! If you want to use OpenCycleMap with API key yuo need to change the whole url to something completely different:

```
https://tile.thunderforest.com/cycle/{z}/{x}/{y}.png?apikey=
```

So you have to do this anyways via javascript after initialization...

**Comment by ssaring** [comment]
Sorry for no response, I'm on vacation. It seems that this is not an issue anymore, right?

**Comment by ThomasDaheim** [comment]
Yes, no issue anymore - it only needs an ugly hack in javascript to get it done...
