### ISSUE TITLE
Streets & Labels for ESRI Satellite map

### ISSUE THREAD

**Issue by ThomasDaheim** [ssaring/sportstracker#217]
I have come across something I would like to share: A layer that can be added to the SATELLITE layer to show names of cities, streets, ...

Not sure how this could be done directly in LeafletMapView? I have done by using js that I add in my code (currently still in "ugly hack" phase):

```
// TFE, 20190814: add Hydda roads and labels to SATELLITE layer
var Hydda_RoadsAndLabels = L.tileLayer('https://{s}.tile.openstreetmap.se/hydda/roads_and_labels/{z}/{x}/{y}.png', {
    maxZoom: 18,
    attribution: 'Tiles courtesy of OpenStreetMap Sweden &mdash; Map data &copy; OpenStreetMap contributors'
});
// move to front - one more as used in TrackMap for layer control init
// could be made dynamic by checking layers from controlLayer to find 'Satellite Esri' and +1 to its zindex...
Hydda_RoadsAndLabels.setZIndex(4);
function baseLayerChange(e) {
    var hasLayer = myMap.hasLayer(Hydda_RoadsAndLabels);
    
    if (e.name === 'Satellite Esri') {
        // add if not already there
        if (!hasLayer) {
            myMap.addLayer(Hydda_RoadsAndLabels);
        }
    } else {
        if (hasLayer) {
            myMap.removeLayer(Hydda_RoadsAndLabels);
        }
    }
} 
myMap.on('baselayerchange', baseLayerChange);
```

Playing around on https://leaflet-extras.github.io/leaflet-providers/preview/ I have seen some more layers but none as helpful as this on (e.g. OpenMapSurfer_Hillshade, OpenMapSurfer_ContourLines, even openweathermap info). But could in theory be handled similarly...

**Comment by ssaring** [comment]
Sounds interesting and helpful for your satelite use case. Nice to hear that you're able to access the needed componets via JS.

**Comment by ThomasDaheim** [comment]
Yes, works like a charm (after I learned a lot of things about how to copy with Javascript from within JavaFX ;-))
