### ISSUE TITLE
Failed to parse excersisce file on new Garmin device

### ISSUE THREAD

**Issue by winfried** [ssaring/sportstracker#220]
Hi,

I got a shiny new garmin watch and now SportsTracker fails to parse most of the FIT files, for example of the types 'cycling' and 'other'.

> SEVERE de.saring.sportstracker.gui.dialogs.ExerciseDialogController onImportHrmFile Failed to parse exercise file! 
>kotlin.TypeCastException: null cannot be cast to non-null type kotlin.Short
>	at  de.saring.exerciseviewer.parser.impl.garminfit.FitMessageListener.storeLaps(FitMessageListener.kt:302)
>	at de.saring.exerciseviewer.parser.impl.garminfit.FitMessageListener.getExercise(FitMessageListener.kt:243)
>	at de.saring.exerciseviewer.parser.impl.garminfit.GarminFitParser.parseExercise(GarminFitParser.kt:34)
>	at de.saring.sportstracker.gui.dialogs.ExerciseDialogController.onImportHrmFile(ExerciseDialogController.java:473)

Details on the watch and an offending FIT file can be provided by mail.

**Comment by ssaring** [comment]
Hi Winfried,

sounds interesting, but I need more details. Please provide an example file for reproducing the problem. Which Garmin watch model you are using?

Bye, Stefan

**Comment by winfried** [comment]
Sorry for the delay, I've send details by mail

**Comment by crrodger** [comment]
I am having the same problem, it has been doing this since 27/9/2019. Suspect it is related to a software update on the device that seemed to occur around that time.

Device : Fenix 5x Plus

Happy to provide .fit files if useful.

**Comment by ssaring** [comment]
That's an interesting issue - it seems that the altitude and speed data is now stored in a different way on the Fenix 6 and on Fenix 5 with newer firmware - they're all null. I need to investigate it more in detail.

I've already got an example FIT file from @winfried , unfortunately I can't use it for a commitable unit test. Such a test would be helpful for regression testing.

@crrodger Could you please provide an example FIT file? It would be interesting to see, whether your problem has the same cause.

**Comment by ssaring** [comment]
I've found the cause for the problem, the speed and altitude data is now stored in other attributes for newer Fenix watches.

@crrodger To verify this bugfix I need an example FIT file for reproducing and unit test implementation.

**Comment by ssaring** [comment]
This bug has been fixed and tested with all the private example files got from @winfried . Unfortunately it's not possible to implement a public unit test with them.

**Comment by ssaring** [comment]
Thanks to a provided Garmin Fenix 6 exercise file, there is now a unit test too.

**Comment by crrodger** [comment]
Apologies Stefan. I have been travelling and not checking my email as frequently as I should.

I am happy to send a .fit file I know is a problem, would you prefer I send it to an email address or somewhere else?

**Comment by ssaring** [comment]
@crrodger Thanks for the files you sent by mail. I've already got a Fenix 6 file for automated unit testing, so they're not needed anymore.
But at least I was able to test your files with the bugfixed version, it works fine now.

**Comment by ssaring** [comment]
Here's a workaround for Garmin Fenix 5 / 6 users who don't want to wait until next SportsTracker release - it's a patches version of the ExerciseViewer JAR file for SportsTracker 7.7.0.

Installation instructions:

- Make sure you have SportsTracker version 7.7.0 installed.
- Locate the installation directory of your local SportsTracker application (depending on OS and installer type)
- Locate the file st-exerciseviewer-7.7.0.jar there - this needs to be replaced. It's in one of the lib-subdirectories.
- Download the attached ZIP file which contains the patched ExerciseViewer and unzip it
- Replace the original st-exerciseviewer-7.7.0.jar file with the patched one

[st-exerciseviewer-7.7.0.jar.zip](https://github.com/ssaring/sportstracker/files/4000655/st-exerciseviewer-7.7.0.jar.zip)

**Comment by crrodger** [comment]
Thanks Stefan.

I downloaded the source and built the updated version and everything works well again, thank you.

Craig Rodger
CSE Dev Crew Asia |Principal Software Engineer
Mobile: +61 406 176 831
