### ISSUE TITLE
Missing fit-20.80.0.pom

### ISSUE THREAD

**Issue by asieriko** [ssaring/sportstracker#222]
Hello

It's the first time I'm ussing maven, so maybe I've done something wrong.

I'm trying to compile version 7.7, but I get this error message:

`Failed to execute goal on project st-exerciseviewer: Could not resolve dependencies for project de.saring:st-exerciseviewer:jar:7.7.0: Failed to collect dependencies at com.garmin.fit:fit:jar:20.80.0: Failed to read artifact descriptor for com.garmin.fit:fit:jar:20.80.0: Could not transfer artifact com.garmin.fit:fit:pom:20.80.0 from/to SportsTracker repository (https://saring.de/st-maven-repo/): Connect to saring.de:443 [saring.de/85.13.132.110] failed: Connection timed out (Connection timed out) -> [Help 1]`

It seems that /fit-20.80.0.pom file cannot be accessed

**Comment by ssaring** [comment]
Strange, I've just tried the build with a clean repo - the download works perfectly. 
And the files are all available in the repository at saring.de .

Do you have problems accessing the website https://saring.de ? Could you please retry it?

**Comment by asieriko** [comment]
You are right, I've tried again and it compiled successfully.

Sorry for the inconvenience and thank you for your work.
