### ISSUE TITLE
GPX import issue

### ISSUE THREAD

**Issue by lanthale** [ssaring/sportstracker#226]
I have some GPX files with version 1.1 which are imported, but no data is shown. The GPX files are downloaded from the web from the following adress: [https://www.mtbsepp.de/touren/rotwandhaus-spitzingsee/download](url)

Thank you in advance for the good app. I use it allot and if you need help I can contribute but have no Kotlin expertice (Javafx/Java).

cheers
Clemens

**Comment by ssaring** [comment]
Hi Clemes,

GPX is a very flexible file format for many different aspects and requirements.
The support for GPX in SportsTracker is for training exercises, which always need date, time and duration for being able to compute and derive all the other data for evaluation and statistics. 
The GPX files you referencing from the mtbsepp website are another kind of GPX. They just contain the geo locations and the elevation, nothing more. No date and times, no speed, nothing. From the SportsTracker perspective such files can't be used for exercise entries, therefore such GPX files are not supported. It would be possible to use a default date then (e.g. 1.1.1980 00:00:00), but that's quite confusing too.

I know, it's quite hard to distinguish the GPX variants from the user perspective and it would be good when there would be different file types depending on the usage scenario (just track or training). But that's unfortunately not the case.

Bye, Stefan
