### ISSUE TITLE
Can't import Forerunner 245 .FIT file

### ISSUE THREAD

**Issue by QA-Manager** [ssaring/sportstracker#227]
I just purchased a Forerunner 245; when I try to import a file from it I get 'Failed to read or parse HRM file'. SportsTracker works fine with my FR 230; I am using the same computer, install, etc.

I am running V7.7.0, and have attached the file that won't parse.
[2020-08-29-16-27-53.zip](https://github.com/ssaring/sportstracker/files/5145974/2020-08-29-16-27-53.zip)

SportsTracker is very useful; my thanks to all of the contributors.

**Comment by ssaring** [comment]
I've tested your attached file with the latest SportsTracker 7.7.1 development version, the file can be opened without problems. 
However, it seems that the file doesn't contain any valuable data. Looks like a test recording for just some seconds without GPS connection. So please test again with the latest dev version and reopen this issue in case of problems.

Bye, Stefan
