### ISSUE TITLE
Maximum and minimum statistics are confusing

### ISSUE THREAD

**Issue by QA-Manager** [ssaring/sportstracker#231]
The statistics have sections labeled 'Minimum' and 'Maximum' (singular, not plural), followed by a distance and other statistics. However, these are not singular maxima and minima - that is, they may represent multiple different exercise entries. One entry may provide the maximum distance - 20km - and another entry on another day may provide the maximum speed - 3 minutes/km. However, since the heading is singular - 'Maximum' - and the first statistic under each heading is 'Distance', it easy to assume that all of the statistics in that section represent the same exercise event.

I would label these as 'Maximums' and 'Minimums' to make it clear that they are all independent measures/events, or I would preface each line with 'Min' or 'Max'. That is 'Distance' would become 'Min Distance', 'Avg. Speed' would become 'Min Avg. Speed', etc. Putting something other than 'Distance' as the first entry under the heading would also make it easier to understand that the entries don't all refer to the same event.

**Comment by ssaring** [comment]
Good point. This is just a tiny change, but it improves the usability. I agree, the current wording can be misunderstood.
This will be changed, unfortunately the translations will be lost and need to be updated too. Anyway...

Thanks for the hint.

**Comment by ssaring** [comment]
Has been fixed (on master branch). The Statistics Result Dialog now uses plural naming.
