### ISSUE TITLE
Gpx import improvements

### ISSUE THREAD

**Issue by odlg** [ssaring/sportstracker#233]
I tried to import a gpx file from gadgetbridge - heartrate was not shown. Attached patch fixes this.

[hr.patch.txt](https://github.com/ssaring/sportstracker/files/5203717/hr.patch.txt)

**Comment by ssaring** [comment]
Thanks for the patch, I've integrated it to master.

Could you please file a PullRequest and include an example file and a unit test next time?
This makes the integration easier, currently I can't test nothing. Tests are also useful in regression later on.
