### ISSUE TITLE
FIT file does not show well

### ISSUE THREAD

**Issue by janlul** [ssaring/sportstracker#234]
I loaded a FIT file and it does not show:
- Hearth rate zones, device nor type in Exercise Main tab
- Anything in Exercise Track tab
The latter being very interesting for the Exercise Measurement tab shows content so the individual point seem to be loaded.

**Comment by ssaring** [comment]
Please provide more info on this issue (Garmin device model, ST version etc.) and attach an example file for reproducing the problem.

Heart rate zones are not supported for Garmin devices, this data is specific for Polar watches.

**Comment by janlul** [comment]
Hi Stefan,

First of all thanks for this software, it really helps me keeping track of training effort and equipment wear. I used to work out with an Edge800 but upgraded to a watch lately.
,

Attached an example file. This was generated by a Suunto Spartan Sport HR Baro watch. Which is also readable in the file I found out.
If hearth rate zones are not automatically loaded, could they be made editable in preferences? You can then always overwrite them if they are in an import.

Sincere regards

 Peter

**Comment by ssaring** [comment]
Hi Peter, 

interesting to hear that Suunto watches are using the FIT file format too, great :)
Unfortunately I can't find any attachment here...

Bye, Stefan

**Comment by janlul** [comment]
Maybe this works better, apparently .fit does not pass Github upload system.
[20201023-1500.fit.zip](https://github.com/ssaring/sportstracker/files/5454144/20201023-1500.fit.zip)
Apparently it is the only file type supported, to my surprise since it is a little bit harder to parse. However Bsecamp could handle it so it is not a very rare type of .fit I think.

**Comment by ssaring** [comment]
Now I've got your test file, thanks. There are no loading errors and the data displayed looks quite OK. Except there is no track data available, has this been recorded and stored in the FIT file?

Has this file been downloaded directly from the watch or was there an conversion process?

**Comment by janlul** [comment]
Yep I assume with certainty that track data is available, for loading it in Basecamp shows the track.

**Comment by janlul** [comment]
And yes it came directly from the watch, hence all details are in. Ever since I noticed they get lost if you run it through converters I store the originals.

**Comment by ssaring** [comment]
Interesting, needs to be checked. Thanks for the info.

**Comment by ssaring** [comment]
Fixed, track data is no displayed properly for Suunto Spartan watches. I've used your example file for an unit test, I hope it's OK for you.

The changes are available in the master branch.
