### ISSUE TITLE
Building with a local copy of OpenJFX

### ISSUE THREAD

**Issue by asomers** [ssaring/sportstracker#238]
I'm trying to compile sportstracker with Maven.  But repo.maven.apache.org does not host a copy of OpenJFX for my operating system (FreeBSD).  Instead, I need to use the locally installed version in /usr/local/openjfx14 .

```
ERROR] Failed to execute goal on project leafletmap: Could not resolve dependencies for project de.saring:leafletmap:jar:1.0.5-SNAPSHOT: The following artifacts could not be resolved: org.openjfx:javafx-fxml:jar:${javafx.platform}:14, org.openjfx:javafx-controls:jar:${javafx.platform}:14, org.openjfx:javafx-graphics:jar:${javafx.platform}:14, org.openjfx:javafx-base:jar:${javafx.platform}:14, org.openjfx:javafx-web:jar:${javafx.platform}:14, org.openjfx:javafx-media:jar:${javafx.platform}:14: Failure to find org.openjfx:javafx-fxml:jar:${javafx.platform}:14 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
```
I'm not familiar with Maven.  Can you please suggest what I should do to convince Maven to use the local installation?

**Comment by ssaring** [comment]
I see, you're trying to get ST running on FreeBSD. As far as I know there are no OpenJFX builds from Gluon available for FreeBSD, the OpenJFX Jars require native libraries as well. Have you build them by your own?

**Comment by asomers** [comment]
I don't know what Gluon is, but OpenJFX is in FreeBSD's regular package repository.  It's got a few patches compared to upstream's, like this brilliant one:
```diff
--- modules/javafx.graphics/src/main/java/com/sun/javafx/tk/Toolkit.java.orig	2020-07-17 10:21:33 UTC
+++ modules/javafx.graphics/src/main/java/com/sun/javafx/tk/Toolkit.java
@@ -186,6 +186,8 @@ public abstract class Toolkit {
             return DEFAULT_TOOLKIT;
         } else if (PlatformUtil.isLinux()) {
             return DEFAULT_TOOLKIT;
+        } else if (PlatformUtil.isFreeBSD()) {
+            return DEFAULT_TOOLKIT;
         } else if (PlatformUtil.isIOS()) {
             return DEFAULT_TOOLKIT;
         } else if (PlatformUtil.isAndroid()) {
```

**Comment by ssaring** [comment]
Interesting. Gluon is the company also responsible for OpenJFX packaging and distribution.
I don't know how FreeBSD provides this dependencies in the OpenJDK installation, are they available by default to all applications? Then it might be sufficient just to remove the OpenJFX dependencies in all the pom.xml files.

**Comment by asomers** [comment]
That doesn't seem to work.  The build can't find the installed version of openjfx.  Do you have any idea how to specify the path to it?
```
INFO] --- kotlin-maven-plugin:1.4.0:compile (compile) @ leafletmap ---
[ERROR] /usr/home/somers/src/github/ssaring/sportstracker/leafletmap/src/main/kotlin/de/saring/leafletmap/LeafletMapView.kt: (3, 8) Unresolved reference: javafx
...
```

**Comment by ssaring** [comment]
I assume that the system-installed OpenJFX libraries need to be included as modules in the build process (not as JARs). Without being able to test I can't thell you how this can be done easily. I think you need to research that - sorry.
