### ISSUE TITLE
Map doesn't work

### ISSUE THREAD

**Issue by molkemon** [ssaring/sportstracker#243]
Hi, 

new user here. On current version, when I import a gpx file it correctly parses the data points for elevation/heartrate etc, but the Track/Map pane remains empty. Not sure if it's my file or some other problem. I used native Windows installer from sourceforge. 

My test .gpx file: https://www.dropbox.com/s/etco4iqpoupn1p3/test.gpx?dl=0

**Comment by ssaring** [comment]
It looks like this GPX file contains some special data which can't be handled, it throws an exception internally.
What's the source of this GPX file, some special device or is it from a converter tool?

**Comment by molkemon** [comment]
It's a gpx file exported from the app Notify for Amazfit (which itself gets it's data from an Amazfit Band 5).
It's weird though as the file itself does open correctly in the exercise viewer, just the map data doesn't (I also checked the file in editor, to me it looks like it's according to specification).

**Comment by ssaring** [comment]
Your attached test file is an interesting corner case. It contains always the same altitude of 222 m, no meter more or less. This results in an range of 0 for the height axis, which can't be displayed by the diagram component. You seem to live in a very flat area ;)
Anyway, needs to be fixed...

**Comment by ssaring** [comment]
Has been fixed with commit 7624c96706641edb1c598d2d4beba18472a5b539 (on master branch). 
This problem occurred both in the Diagram and Track Panel. Thanks for reporting.
