### ISSUE TITLE
[Request] Include Sportstracker in Debian Repo

### ISSUE THREAD

**Issue by Ged296123** [ssaring/sportstracker#245]
Thank you for a great app!
I was wondering if you would like to include Sportstracker in the Debian repositories.
As I'm not technical, I would feel safer to download the app from official OS repos to make sure that there arw no conflicts with my system runtimes/libraries.
Thanks again.

**Comment by ssaring** [comment]
Thanks for your feedback. 
As I don't use Debian Linux as my primary working environment I don't plan to take over the packaging and the maintainance for adding SportsTracker to the official Debian repos. If anybody else wants to do that, would be great.

Therefore I close this Request, as this will not be provided from this project.

**Comment by Ged296123** [comment]
Thank you again for developing SportsTracker and responding.
