### ISSUE TITLE
No compiled versions for Java versions lower then version 12.

### ISSUE THREAD

**Issue by JoopN** [ssaring/sportstracker#247]
Going to Github is one thing, deleting everything is something else. I'm new to Linux and have a Raspberry Pi 400. Migrating from an other OS to Linux and several others. One thing I can't  use at the moment is compiling from source. So why not have compiled versions from older version of SportsTracker? I didn't get an update of Java. Seems your now on 12 or above;
Error: LinkageError occurred while loading main class de.saring.sportstracker.STMain
	java.lang.UnsupportedClassVersionError: de/saring/sportstracker/STMain has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 55.0

As every other system on the www does  have pages about SportsTracker,  but  with the wrong link to SourceForce. So also there a dead end. 
Now  what?

**Comment by ssaring** [comment]
Raspberry Pi is Linux on ARM, there were never binary SportsTracker packages for that platform (available for Linux x64 only). These packages include the Java Runtime, so they need to fit to the OS and the architecture.

Therefore you need to compile SportsTracker by yourself, older versions of the SportsTracker source code can be found on the GitHub release page: https://github.com/ssaring/sportstracker/releases

The SourceForge download archive has been removed for several reasons, see the announcement for further details. AFAIK the current documentation / website does not contain any links to that SourceForge archive anymore. If so, please provide links for correction.
