### ISSUE TITLE
SportsTracker 7.8.0 import of TCX-files

### ISSUE THREAD

**Issue by winne-jena** [ssaring/sportstracker#249]
I tried to open a  xxx.tcx file by 'open with'.  SportsTracker opened, empty windows with 'no units'. With =>File=>open with Exercise Viewer, I got everything, but only if the file-Address is short (<255 characters) an noch possibility to store.
Is there a way to just open a txc-file with the Exercise Viewer? Why the restriction to 255 characters?

**Comment by ssaring** [comment]
Closing this isse due to missing error detail reports.
