### ISSUE TITLE
LeafletMap Event listeners not fired

### ISSUE THREAD

**Issue by aviollet** [ssaring/sportstracker#250]
Hi
i'm new to LeafletMap. Despite i can easily load the map, and markers, i can't get the event listeners triggered.
Using : de.saring.leafletmap 1.0.5 (the only one available from mvnrepo)
Java 11 (tried with Java 17, but same problem)

While the markers are correctly set, the events code for "setOnZoom" and "setOnZoomFinished"  is never called from the snippet below  (I'm then zooming on the map, both mouse clicking and using the Zoom Control):

        MapConfig mapConfig = new MapConfig(
                Arrays.asList(MapLayer.values()),
                new ZoomControlConfig(true, ControlPosition.BOTTOM_LEFT),
                new ScaleControlConfig(true, ControlPosition.BOTTOM_LEFT, true));
        CompletableFuture cfMapLoadState = leafletMap.displayMap(mapConfig);

        cfMapLoadState.whenComplete(new BiConsumer() {
            @Override
            public void accept(Object workerState, Object o2) {
                if (workerState == Worker.State.SUCCEEDED) {

                    leafletMap.setOnZoom(new EventHandler<ZoomEvent>() {
                        @Override
                        public void handle(ZoomEvent zoomEvent) {
                            LogC.log(getClass(), "setOnZoom",LogC.LOG_DBG);
                        }
                    });
                    leafletMap.setOnZoomFinished(new EventHandler<ZoomEvent>() {
                        @Override
                        public void handle(ZoomEvent zoomEvent) {
                            LogC.log(getClass(), "setOnZoomFinished",LogC.LOG_DBG);
                        }
                    });

                    leafletMap.setView(new LatLong(52.5172, 13.4040), 9);
                    leafletMap.addMarker(
                            new LatLong(52.5172, 13.4040),
                            "Berlin",
                            ColorMarker.BLUE_MARKER, 0);

                    leafletMap.addMarker(
                            new LatLong(45.5172, 10.4040),
                            "city",
                            ColorMarker.RED_MARKER, 0);
                }
            }
        });

i know it's not the best place, but if someone can let me know if it's possible to get some Marker Clicked event... that would be nice.  Doesn't seem to exist as far as I can see... 

Thanks a lot for your help
BR
Alex

**Comment by ssaring** [comment]
Hi Alex,

you probably mix up the event handling of the JavaFX StackPane component and the zoom behavior of a map. LeafletMapView extends the JavaFX container class StackPane and inherits the generic zoom event handling methods. These event handling methods are not related to the zooming in the Leaflet map!
See API doc of [StackPane](https://docs.oracle.com/javase/10/docs/api/javafx/scene/layout/StackPane.html) for further details.

The LeafletMap component currently does not support the zoom event handling and the marker click event handling as there was no demand for that yet. It shouldn't be that hard to add these features, in case you want to implement them. 

Bye, Stefan
