### ISSUE TITLE
'View HRM File' always shows sport type as 'Treadmill'

### ISSUE THREAD

**Issue by The-QA-Geek** [ssaring/sportstracker#264]
Most of my running is outside; when I look at the 'Main' tab on the Exercise dialog I see:
- Sport Type: Running
- Sport Subtype: Street run

However, when I look at the 'Main' tab on the 'View HRM file' dialog, it shows "Sport Type: Running / Treadmill".

This is with Sportstracker 8.0.0, after I upgraded from 7.9.1; I don't know what the HRM dialog showed before the upgrade.

**Comment by ssaring** [comment]
That's easy to explain: in the SportsTracker Exercise the sport type and subtype are your personal selections in SportsTracker. In ExerciseViewer (started via View HRM file) you see the sport type and subtype of your training device (e.g. the watch). It just shows what has been configured there.
So in your case you're your exercise seems to be recorded as a treadmill run.
