### ISSUE TITLE
Migrate issue tracker to GitHub

### ISSUE THREAD

**Issue by ssaring** [ssaring/sportstracker#62]
I see in the log that in 2014 the decision was made to migrate the project repository from SourceForge to GitHub but keep the issue tracker here. What are your thought on this today? In my opinion GitHub is superior compering to what SourceForge has to offer.

Reported by: hubertbanas

**Comment by ssaring** [comment]
All open and closed bugs and feature requests have been migrated from SourceForge to GitHub by using https://github.com/cmungall/gosf2github

Because GitHub and SourceForge users are not unique and can't be mapped, all the migrated issues have been created by me (username ssaring). At least the original names of the creators and contributors can be found in the issue text and comments.

Unfortunately the migration of attachments (e.g. screenshots and exercise files) is not supported, in case of demand they need to be looked up in the appropriate SourceForge issues.

The issue tracker on SourceForge will now be closed (will remain read-only), all users needs to use GitHub instead.

**Comment by hubertbanas** [comment]
Awesome!
